# Intro to Numpy

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/ahmadalawad/Desktop/all-cf-material/401/python/amman-python-401d7/class-11/demo/chess-board/.venv/lib/python3.8/site-packages/numpy/__init__.py'>

In [3]:
nums = [3,7,5,8]

In [4]:
nums

[3, 7, 5, 8]

In [5]:
np.array

<function numpy.array>

In [6]:
nums_as_np = np.array(nums)

In [7]:
nums_as_np

array([3, 7, 5, 8])

In [8]:
type(nums_as_np)

numpy.ndarray

In [25]:
nums_as_np.shape

(4,)

In [10]:
two_dim_array = np.array([ [2,5,6] , [8,3,5] ])

In [12]:
two_dim_array

array([[2, 5, 6],
       [8, 3, 5]])

In [14]:
two_dim_array.shape

(2, 3)

In [15]:
two_dim_array[0]

array([2, 5, 6])

In [16]:
two_dim_array[0,2]

6

In [21]:
two_dim_array[:1]

array([[2, 5, 6]])

In [27]:
two_dim_array[:,2]

array([6, 5])

## Dealing with files

In [30]:
with open('student_scores.csv') as f:
    print(f.read())
    # '2.5,21' => ['2.5', '21']

Hours,Scores
2.5,21
5.1,47
3.2,27
8.5,75
3.5,30
1.5,20
9.2,88
5.5,60
8.3,81
2.7,25
7.7,85
5.9,62
4.5,41
3.3,42
1.1,17
8.9,95
2.5,30
1.9,24
6.1,67
7.4,69
2.7,30
4.8,54
3.8,35
6.9,76
7.8,86



In [31]:
dataset = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=True)

In [32]:
dataset.shape

(25, 2)

In [33]:
dataset

array([[ 2.5, 21. ],
       [ 5.1, 47. ],
       [ 3.2, 27. ],
       [ 8.5, 75. ],
       [ 3.5, 30. ],
       [ 1.5, 20. ],
       [ 9.2, 88. ],
       [ 5.5, 60. ],
       [ 8.3, 81. ],
       [ 2.7, 25. ],
       [ 7.7, 85. ],
       [ 5.9, 62. ],
       [ 4.5, 41. ],
       [ 3.3, 42. ],
       [ 1.1, 17. ],
       [ 8.9, 95. ],
       [ 2.5, 30. ],
       [ 1.9, 24. ],
       [ 6.1, 67. ],
       [ 7.4, 69. ],
       [ 2.7, 30. ],
       [ 4.8, 54. ],
       [ 3.8, 35. ],
       [ 6.9, 76. ],
       [ 7.8, 86. ]])

In [37]:
# Avergae number of hours spent studying
hours = dataset[:,0]
avg_studied_hours = np.average(hours)
avg_studied_hours

5.012

In [38]:
np.mean(hours)

5.012

In [39]:
np.median(hours)

4.8